apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-template
  description: Python app scaffolding template
  tags:
    - 'devcontainers'
  annotations:
    devcontainers.io/vscode-url: 'vscode://devcontainers/open?url=https%3A%2F%2Fgithub.com%2Fsumit-ct-02%2Fpython-backstage'
    github.com/project-slug: sumit-ct-02/python-backstage
spec:
  type: service
  owner: sumit
  lifecycle: experimental
