apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-template
  description: Python app scaffolding template
  annotations:
    github.com/project-slug: KarthikNarsapur/python-backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: narsapurkarthik
  lifecycle: experimental
