name: Run Flask App on EC2 Runner

on:
  workflow_dispatch:

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    environment: Backstage
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Verify AWS credentials
        run: |
          echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Start EC2 runner
      #   id: start-ec2-runner
      #   uses: machulav/ec2-github-runner@v2
      #   with:
      #     mode: start
      #     github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      #     ec2-image-id: ami-0e35ddab05955cf57  
      #     ec2-instance-type: t2.micro
      #     subnet-id: subnet-055bc0f5f47a83b3a  
      #     security-group-id: sg-08baa8217c415d23c
      #     aws-resource-tags: >
      #       [
      #         {"Key": "Name", "Value": "ec2-github-runner"},
      #         {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
      #       ]
      - name: Launch EC2 instance
        run: |
          USER_DATA=$(base64 -w0 <<EOF
          #!/bin/bash
          apt update
          # Make A Directory 
          cd /home/ubuntu
          mkdir actions-runner && cd actions-runner     
          # Download the latest runner package
          curl -o actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
          #Extract the installer
          tar xzf ./actions-runner-linux-x64-2.323.0.tar.gz
          # Create the runner and start the configuration experience
          ./config.sh --url https://github.com/sumit-ct-02/python-backstage --token BRPOKWK532YSQI6FZHEHYX3ICBR7W
          # Last step, run it!
          ./run.sh
          EOF
          )
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0e35ddab05955cf57 \
            --instance-type t2.micro \
            --subnet-id subnet-055bc0f5f47a83b3a \
            --security-group-ids sg-08baa8217c415d23c \
            --user-data $USER_DATA \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

  run-flask:
    name: Run Flask App
    needs: start-runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flask
          sudo apt update
          sudo apt install -y jq curl

      - name: Start Flask app
        run: |
          nohup python main.py &
        env:
          FLASK_ENV: development

      - name: Wait and keep server alive
        run: |
           PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
           echo "Flask app started at: http://$PUBLIC_IP:5000"
           echo "On EC2 instance ID: ${{ needs.start-runner.outputs.ec2-instance-id }}"
           sleep 300

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - run-flask
    runs-on: ubuntu-latest
    environment: Backstage
    steps:
      - name: Stop EC2
        if: ${{ always() }}
        run: |
          aws ec2 terminate-instances --instance-ids ${{ needs.start-runner.outputs.ec2-instance-id }}
